name: Build python package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tree tool
        run: sudo apt-get install tree

      - name: Display directory tree before build
        run: tree .

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
